### ISSUE TITLE
Error : /etc/cont-init.d/90-data_location.sh exiting 2

### ISSUE THREAD

**Issue by Will711990** [bilogic/ha-addons#2]
Hi,

the add-on cannot boot, and this error appears:

```
goroutine 25 [running]:
github.com/go-chi/chi/v5.(*Mux).handle(0xc0004b8040?, 0xa?, {0xc0004b8040?, 0x1?}, {0x7faa08260aa8?, 0xc000512018?})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:403 +0x2c5
github.com/go-chi/chi/v5.(*Mux).Handle(0xc0004d1980, {0xc0004b8040, 0xa}, {0x7faa08260aa8, 0xc000512018})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:116 +0x9f
github.com/navidrome/navidrome/server.(*Server).initRoutes.func1({0x27a2058, 0xc0004d1980})
	/__w/navidrome/navidrome/server/server.go:185 +0x1f4
github.com/go-chi/chi/v5.(*Mux).Group(0x278f320?, 0xc000219e40)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:271 +0x38
github.com/navidrome/navidrome/server.(*Server).initRoutes(0xc000534000)
	/__w/navidrome/navidrome/server/server.go:181 +0x354
github.com/navidrome/navidrome/server.New({0x279f8a0, 0xc000516010}, {0x2791a68, 0xc000512018})
	/__w/navidrome/navidrome/server/server.go:40 +0xe8
github.com/navidrome/navidrome/cmd.CreateServer({0x0?, 0x0?})
	/__w/navidrome/navidrome/cmd/wire_gen.go:35 +0xaa
github.com/navidrome/navidrome/cmd.runNavidrome.startServer.func1()
	/__w/navidrome/navidrome/cmd/root.go:103 +0x38
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96
Error : /etc/cont-init.d/90-data_location.sh exiting 2
```

After, the addon try to boot in loop...

**Comment by bilogic** [comment]
Hi,

Which version is this and what is your ND_BASEURL?

**Comment by Will711990** [comment]
Oh sorry for the lack of information !
Version : 1.0.36
ND_BASEURL : « . » (just a dot)

**Comment by bilogic** [comment]
Set ND_BASEURL to / instead, i will get it fixed in a bit thanks

**Comment by Will711990** [comment]
It works !!
Thank you very much :-)

**Comment by bilogic** [comment]
This has been rectified in `1.0.37`
